In [58]:
import numpy as np

In [59]:
list1 = [1,2,3]
print('list type: ', type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1)
print(array1.shape)

list type:  <class 'list'>
<class 'numpy.ndarray'>
[1 2 3]
(3,)


In [60]:
array2 = np.array([[1,2,3,],
                  [2,3,4]])
print(array2)
print(array2.shape)

[[1 2 3]
 [2 3 4]]
(2, 3)


In [61]:
array3 = np.array([[1,2,3]])
print(array3.shape)

(1, 3)


In [62]:
print(array1.ndim)
print(array2.ndim)
print(array3.ndim)

1
2
2


ndarray의 데이터 타입

In [12]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [13]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)

['1' '2' 'test'] <U11


In [14]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [15]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)


[1. 2. 3.] float64


In [16]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [17]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


ndarray를 편리하게 생성하기-arange,zeros,ones

In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [19]:
#(3,2) shape를 가지는 모든 원소가 0, dtype은 int32인 ndarray 생성
zero_array = np.zeros((3,2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
#(3,2) shpae를 가지는 모든 원소가 1인 ndarray 생성
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


ndarray의 차원과 크기를 변경하는 reshape

In [4]:
array1 = np.arange(10)
print(array1)

#(2,5) shape로 변환
array2 = array1.reshape(2, 5)
print(array2)

#(5,2) shape로 변환
array3 = array1.reshape(5,2)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [5]:
array1.reshape(4,3)

ValueError: cannot reshape array of size 10 into shape (4,3)

In [6]:
array1 = np.arange(10)
print(array1)

array2 = array1.reshape(-1, 5)
print(array2.shape)

array3 = array1.reshape(5, -1)
print(array3.shape)

[0 1 2 3 4 5 6 7 8 9]
(2, 5)
(5, 2)


In [26]:
array1 = np.arange(10)
array4 = array1.reshape(-1, 4)

ValueError: cannot reshape array of size 10 into shape (4)

In [27]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print(array3d.tolist())

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [30]:
#3차원 ndarray를 2차원 ndarray로 변환하되 칼럼 갯수는 1개
array5 = array3d.reshape(-1,1)
print(array5.tolist())
print(array5)

[[0], [1], [2], [3], [4], [5], [6], [7]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [32]:
#1차원 ndarray를 2차원 ndarray로 변환하되 칼럼 갯수는 1개
array6 = array1.reshape(-1,1)
print(array6.tolist())
print(array6.shape)

[[0], [1], [2], [3], [4], [5], [6], [7]]
(8, 1)


In [33]:
#3차원 array를 1차원으로 변환
array1d = array3d.reshape(-1,)
print(array1d)

[0 1 2 3 4 5 6 7]


인덱싱

In [10]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터값을 의미
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [11]:
print(f'맨 뒤의 값: {array1[-1]}, 맨 뒤에서 두 번째 값: {array1[-2]}')

맨 뒤의 값: 9, 맨 뒤에서 두 번째 값: 8


In [12]:
# 수정
array1[0] = 9
array1[8] = 0
print(array1)

[9 2 3 4 5 6 7 8 0]


In [15]:
# 다차원
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print(f'(row=0, col=0), index 가리키는 값: {array2d[0, 0]}')
print(f'(row=0, col=1), index 가리키는 값: {array2d[0, 1]}')
print(f'(row=1, col=0), index 가리키는 값: {array2d[1, 0]}')
print(f'(row=2, col=2), index 가리키는 값: {array2d[2, 2]}')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0), index 가리키는 값: 1
(row=0, col=1), index 가리키는 값: 2
(row=1, col=0), index 가리키는 값: 4
(row=2, col=2), index 가리키는 값: 9


슬라이드 인덱싱

In [16]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [13]:
array1 = np.arange(1, 10)
#위치 인덱스 0-2(2 포함)추출
array4 = array1[0:3]
print(array4)
#위치 인덱스 3부터 마지막까지 추출
array5 = array1[3:]
print(array5)
#위치 인덱스로 전체 추출
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(f'array2d:\n {array2d}')

print(f'array2d[0:2, 0:2]:\n {array2d[0:2, 0:2]}')
print(f'array2d[1:3, 0:3]:\n {array2d[1:3, 0:3]}')
print(f'array2d[1:3, :]:\n {array2d[1:3, :]}')
print(f'array2d[:, :]:\n {array2d[:, :]}')
print(f'array2d[:2, 1:]:\n {array2d[:2, 1:]}')

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2]:
 [[1 2]
 [4 5]]
array2d[1:3, 0:3]:
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :]:
 [[4 5 6]
 [7 8 9]]
array2d[:, :]:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:]:
 [[2 3]
 [5 6]]


팬시 인덱싱


In [38]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print(f'array2d[[0, 1], 2] => {array3.tolist()}')

array4 = array2d[[0, 1], 0:2]
print(f'array2d[[0, 1], 0:2] => {array4.tolist()}')

array5 = array2d[[0, 1]]
print(f'array2d[[0, 1]] => {array5.tolist()}')

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


불린 인덱싱

In [39]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 적용
array3 = array1d[array1d > 5]
print(f'array1d > 5 불린 인덱싱 결과 값: {array3}')

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [40]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [41]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True, True])
array3 = array1d[boolean_indexes]
print(f'array1d > 5 불린 인덱싱 결과 값: {array3}')

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [42]:
array1d = np.arange(1, 10)
target = []
#불린 인덱싱을 사용하지 않을 경우
for i in range(0, 9):
    if array1d[i] > 5:
        target.append(array1d[i])

array_selected = np.array(target)
print(array_selected)

[6 7 8 9]


In [43]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print(array4)

[6 7 8 9]


sort()와 argsort()

In [46]:
org_array = np.array([3, 1, 9, 5])
print(f'원본 행렬: {org_array}')

# np.sort()로 정렬
sort_array1 = np.sort(org_array)
print(f'np.sort() 결과: {sort_array1}')
print(f'np.sort() 후 원본: {org_array}')

# ndarray.sort()로 정렬
sort_array2 = org_array.sort()
print(f'ndarray.sort() 결과: {sort_array2}')
print(f'ndarray.sort() 후 원본: {org_array}')

원본 행렬: [3 1 9 5]
np.sort() 결과: [1 3 5 9]
np.sort() 후 원본: [3 1 9 5]
ndarray.sort() 결과: None
ndarray.sort() 후 원본: [1 3 5 9]


In [48]:
# 내림차순 정렬
sort_array1_desc = np.sort(org_array)[::-1]
print(f'내림차순 정렬: {sort_array1_desc}')

내림차순 정렬: [9 5 3 1]


In [50]:
array2d = np.array([[8,12],
                   [7,1]])

sort_array2d_axis0 = np.sort(array2d, axis = 0)
print(f'row 방향으로 정렬:\n {sort_array2d_axis0}')

sort_array2d_axis1 = np.sort(array2d, axis = 1)
print(f'column 방향으로 정렬:\n {sort_array2d_axis1}')

row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
column 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


정렬 행렬의 인덱스 반환

In [51]:
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(type(sort_indices))
print(f'행렬 정렬 시 원본 행렬의 인덱스: {sort_indices}')

<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [52]:
org_array = np.org_array = np.array([3,1,9,5])
sort_indices_desc = np.argsort(org_array)[::-1]
print(f'행렬 내림차순 정렬시 원본 행렬의 인덱스: {sort_indices_desc}')

행렬 내림차순 정렬시 원본 행렬의 인덱스: [2 3 0 1]


In [53]:
import numpy as np
name_array = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_array = np.array([78, 95, 84, 98, 88])

sort_indices_asc = np.argsort(score_array)
print(f'성적 오름차순 정렬 시 score_array의 인덱스: {sort_indices_asc}')
print(f'성적 오름차순 정렬 시 score_array의 인덱스: {name_array[sort_indices_asc]}')

성적 오름차순 정렬 시 score_array의 인덱스: [0 2 4 1 3]
성적 오름차순 정렬 시 score_array의 인덱스: ['John' 'Sarah' 'Samuel' 'Mike' 'Kate']


행렬 내적


In [54]:
A = np.array([[1,2,3],
             [4,5,6]])
B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_product = np.dot(A,B)
print(f'행렬 내적 결과:\n {dot_product}')

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


In [57]:
A = np.array([[1,2],
             [3,4]])
transpose_mat = np.transpose(A)
print(f'np.transpose(A):\n {transpose_mat}')
print(f'A.T:\n {A.T}')

np.transpose(A):
 [[1 3]
 [2 4]]
A.T:
 [[1 3]
 [2 4]]
